# Generated by Django 3.2.8 on 2024-01-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('customer_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='senderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='ticketID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_support.ticket'),
        ),
    ]
